MODULE constants_mod
	IMPLICIT NONE	
    
	INTEGER, PARAMETER :: N = 2200
    INTEGER, PARAMETER :: nx = 100
    INTEGER, PARAMETER :: ny = 1
    INTEGER, PARAMETER :: nz = 1
    INTEGER, PARAMETER :: nb = 1
    INTEGER, PARAMETER :: ndims = 1
    INTEGER, PARAMETER :: nt = 200
    INTEGER, PARAMETER :: num_nodes = 2 ! FIXED NUMBER OF NODES PER TREE

END MODULE constants_mod
