MODULE constants_mod
	IMPLICIT NONE	
    
	INTEGER, PARAMETER :: N = 320000
    INTEGER, PARAMETER :: nx = 50
    INTEGER, PARAMETER :: ny = 1
    INTEGER, PARAMETER :: nz = 1
    INTEGER, PARAMETER :: nb = 1
    INTEGER, PARAMETER :: ndims = 1
    INTEGER, PARAMETER :: nt = 1

END MODULE constants_mod
